In [17]:
import pandas as pd

In [34]:
data = pd.read_csv("/projects/net_contrast_classification/contrast_phase/data/cleaned_data/cleaned_data.csv")
batch3 = data[data["Destination Folder"].str.contains("DICOM-batch3")].reset_index(drop=True)
batch3

,Original File,Destination Folder,New File,SubjectKeyRadiology,ExamDate,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,...,ImageOrientationPatientDICOM,ConversionSoftware,ConversionSoftwareVersion,BodyPartExamined,RawImage,SliceThickness,AcquisitionTime_sec,DICOM_phase,MatchKey,exist_on_server
0,../DICOM-batch3\NKI-d23231-00-0201\20130107 CT...,DICOM-batch3-kalina01,NET_0000_0000.nii.gz,NKI-d23231-00-0201,2013-01-07,NET_0000_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,48979.90000,NaN,NKI-d23231-00-0201_20130107_kalina01_0000.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
1,../DICOM-batch3\NKI-d23231-00-0202\20090914 Ab...,DICOM-batch3-kalina01,NET_0001_0000.nii.gz,NKI-d23231-00-0202,2009-09-14,NET_0001_0000.nii.gz,Yes,Arterial,Too Early,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,44652.16987,Arterial,NKI-d23231-00-0202_20090914_kalina01_0001.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
2,../DICOM-batch3\NKI-d23231-00-0204\20080123 Th...,DICOM-batch3-kalina01,NET_0002_0000.nii.gz,NKI-d23231-00-0204,2008-01-23,NET_0002_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,50240.38607,NaN,NKI-d23231-00-0204_20080123_kalina01_0002.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
3,../DICOM-batch3\NKI-d23231-00-0205\20151211 CT...,DICOM-batch3-kalina01,NET_0003_0000.nii.gz,NKI-d23231-00-0205,2015-12-11,NET_0003_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,48523.01072,Portal,NKI-d23231-00-0205_20151211_kalina01_0003.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
4,../DICOM-batch3\NKI-d23231-00-0206\20080911 Ab...,DICOM-batch3-kalina01,NET_0004_0000.nii.gz,NKI-d23231-00-0206,2008-09-11,NET_0004_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,48608.81460,NaN,NKI-d23231-00-0206_20080911_kalina01_0004.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5976,../DICOM-batch3\NKI-d23231-00-0888\20220420 CT...,DICOM-batch3-kalina99,NET_5827_0000.nii.gz,NKI-d23231-00-0888,2022-04-20,NET_5827_0000.nii.gz,Yes,Portal,Just Right,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,54796.11932,Portal,NKI-d23231-00-0888_20220420_kalina99_5827.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
5977,../DICOM-batch3\NKI-d23231-00-0888\20230424 CT...,DICOM-batch3-kalina99,NET_5828_0000.nii.gz,NKI-d23231-00-0888,2023-04-24,NET_5828_0000.nii.gz,Yes,Arterial,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,43545.56100,Arterial,NKI-d23231-00-0888_20230424_kalina99_5828.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
5978,../DICOM-batch3\NKI-d23231-00-0888\20230424 CT...,DICOM-batch3-kalina99,NET_5829_0000.nii.gz,NKI-d23231-00-0888,2023-04-24,NET_5829_0000.nii.gz,Yes,Portal,Just Right,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,43580.13800,NaN,NKI-d23231-00-0888_20230424_kalina99_5829.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
5979,../DICOM-batch3\NKI-d23231-00-0888\20230801 CT...,DICOM-batch3-kalina99,NET_5830_0000.nii.gz,NKI-d23231-00-0888,2023-08-01,NET_5830_0000.nii.gz,Yes,Arterial,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,42200.65000,Arterial,NKI-d23231-00-0888_20230801_kalina99_5830.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
5980,../DICOM-batch3\NKI-d23231-00-0888\20230801 CT...,DICOM-batch3-kalina99,NET_5831_0000.nii.gz,NKI-d23231-00-0888,2023-08-01,NET_5831_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,42230.04200,NaN,NKI-d23231-00-0888_20230801_kalina99_5831.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...

In [35]:
giovanni_batch3 = pd.read_csv("/projects/net_contrast_classification/contrast_phase/data/giovanni_data/NET_annotations.csv")
christina_batch3 = pd.read_csv("/projects/net_contrast_classification/contrast_phase/data/christina_data/NET_annotations.csv")

print(len(giovanni_batch3), len(christina_batch3))

351 351

In [36]:
print("Overlap between Giovanni and Christina:",len(set(giovanni_batch3["file"]).intersection(christina_batch3["file"])), "samples")
print("Overlap between Giovanni and Kalina:",len(set(giovanni_batch3["file"]).intersection(batch3["file"])), "samples")
print("Overlap between Christina and Kalina:",len(set(batch3["file"]).intersection(christina_batch3["file"])), "samples")

Overlap between Giovanni and Christina: 344 samples
Overlap between Giovanni and Kalina: 344 samples
Overlap between Christina and Kalina: 344 samples

In [42]:
giovanni_batch3 = giovanni_batch3.rename(columns={'no_lesions': 'is_lesionfree'})
christina_batch3 = christina_batch3.rename(columns={'no_lesions': 'is_lesionfree'})

def annot_mapping(data):
    contrast_mapping = {1.0: "Arterial", 2.0: "Portal", 3.0: "Non-contrast"}                       
    time_mapping = {1.0: "Too Early", 2.0: "Just Right", 3.0: "Too Late", 0.0: 0.0}                 
    liver_mapping = {1.0: "Yes", 2.0: "Partially"}                                                  
    lesion_mapping = {True: "Yes", False: "No"}

    data['contrast'] = data['contrast'].map(contrast_mapping)
    data['phase_timing'] = data['phase_timing'].map(time_mapping)
    data['is_liver_imaged'] = data['is_liver_imaged'].map(liver_mapping)
    data.loc[data['file'].notna(), 'is_lesionfree'] = data.loc[data['file'].notna(), 'is_lesionfree'].map(lesion_mapping).fillna("No")

    return data

In [41]:
display(giovanni_batch3.contrast.value_counts(), giovanni_batch3.contrast.isna().sum(),
        giovanni_batch3.phase_timing.value_counts(), giovanni_batch3.phase_timing.isna().sum(),
        giovanni_batch3.is_liver_imaged.value_counts(), giovanni_batch3.is_liver_imaged.isna().sum(),
        giovanni_batch3.is_lesionfree.value_counts(), giovanni_batch3.is_lesionfree.isna().sum())

contrast
2    242
1    107
3      2
Name: count, dtype: int64

np.int64(0)

phase_timing
2    307
3     26
1     16
0      2
Name: count, dtype: int64

np.int64(0)

is_liver_imaged
1    345
2      6
Name: count, dtype: int64

np.int64(0)

is_lesionfree
False    187
True     160
Name: count, dtype: int64

np.int64(4)

In [ ]:
giovanni_batch3 = giovanni_batch3.rename(columns={'no_lesions': 'is_lesionfree'})
christina_batch3 = christina_batch3.rename(columns={'no_lesions': 'is_lesionfree'})

giovanni_batch3 = annot_mapping(giovanni_batch3)
christina_batch3 = annot_mapping(christina_batch3)

In [45]:
giovanni_batch3

,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,ai_segmentation_quality,manual_segmentation_confidence,adjustment_segmentation_difficulty,high_signal_to_noise,metal_artifacts,patient_motion,other,comment,time-stamp
0,NET_0009_0000.nii.gz,Yes,Arterial,Too Early,No,3.0,4.0,2.0,True,False,False,NaN,NaN,1.775307e+09
1,NET_0013_0000.nii.gz,Yes,Arterial,Too Late,No,4.0,3.0,4.0,False,False,False,NaN,NaN,1.775307e+09
2,NET_0017_0000.nii.gz,Yes,Arterial,Just Right,No,2.0,4.0,5.0,False,False,False,NaN,NaN,1.775307e+09
3,NET_0021_0000.nii.gz,Yes,Arterial,Just Right,Yes,NaN,NaN,NaN,False,False,False,NaN,NaN,1.775307e+09
4,NET_0025_0000.nii.gz,Yes,Portal,Just Right,Yes,NaN,NaN,NaN,True,False,False,NaN,NaN,1.775307e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,NET_0508_0000.nii.gz,Yes,Arterial,Just Right,No,3.0,4.0,5.0,False,True,False,NaN,NaN,1.775235e+09
347,NET_0511_0000.nii.gz,Yes,Portal,Just Right,No,3.0,4.0,4.0,True,False,False,NaN,NaN,1.775235e+09
348,NET_0516_0000.nii.gz,Yes,Portal,Just Right,No,4.0,4.0,5.0,False,False,False,NaN,NaN,1.775235e+09
349,NET_0521_0000.nii.gz,Yes,Arterial,Just Right,No,3.0,4.0,3.0,True,False,False,NaN,NaN,1.775235e+09
350,NET_0525_0000.nii.gz,Yes,Portal,Just Right,No,2.0,4.0,5.0,False,False,False,NaN,NaN,1.775235e+09

In [54]:
print(
    "Duplicate files in Giovanni:",
    giovanni_batch3["file"].duplicated().sum()
)

print(
    "Duplicate files in Christina:",
    christina_batch3["file"].duplicated().sum()
)

print(
    "Duplicate files in Kalina:",
    batch3["file"].duplicated().sum()
)

Duplicate files in Giovanni: 7
Duplicate files in Christina: 7
Duplicate files in Kalina: 473

In [56]:
g_dups = giovanni_batch3[
    giovanni_batch3["file"].duplicated(keep=False)
].sort_values("file")

c_dups = christina_batch3[
    christina_batch3["file"].duplicated(keep=False)
].sort_values("file")

k_dups = batch3[
    batch3["file"].duplicated(keep=False)
].sort_values("file")


display(g_dups)
display(c_dups)
display(k_dups)

,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,ai_segmentation_quality,manual_segmentation_confidence,adjustment_segmentation_difficulty,high_signal_to_noise,metal_artifacts,patient_motion,other,comment,time-stamp
187,NET_0000_0000.nii.gz,Yes,Portal,Just Right,Yes,NaN,NaN,NaN,False,True,False,NaN,NaN,1.775235e+09
188,NET_0000_0000.nii.gz,Yes,Portal,Just Right,Yes,NaN,NaN,NaN,False,True,False,NaN,NaN,1.772988e+09
189,NET_0000_0000.nii.gz,Yes,Portal,Just Right,Yes,NaN,NaN,NaN,False,True,False,NaN,NaN,1.772988e+09
222,NET_0058_0000.nii.gz,Yes,Portal,Just Right,No,3.0,4.0,4.0,False,False,False,NaN,NaN,1.775309e+09
223,NET_0058_0000.nii.gz,Yes,Portal,Just Right,No,2.0,3.0,3.0,False,False,False,NaN,likely post interventional treatment,1.773654e+09
97,NET_0314_0000.nii.gz,Yes,Portal,Just Right,Yes,NaN,NaN,NaN,True,False,False,NaN,NaN,1.775232e+09
98,NET_0314_0000.nii.gz,Yes,Portal,Just Right,Yes,NaN,NaN,NaN,False,False,False,NaN,NaN,1.772462e+09
116,NET_0408_0000.nii.gz,Yes,Portal,Too Early,No,4.0,4.0,2.0,False,True,False,NaN,NaN,1.775310e+09
117,NET_0408_0000.nii.gz,Yes,Portal,Too Early,No,4.0,4.0,2.0,False,True,False,NaN,NaN,1.772906e+09
318,NET_0456_0000.nii.gz,Yes,Portal,Just Right,No,3.0,5.0,1.0,False,False,False,NaN,NaN,1.775233e+09
319,NET_0456_0000.nii.gz,Yes,Portal,Just Right,No,3.0,5.0,1.0,False,False,False,NaN,NaN,1.774624e+09
324,NET_0467_0000.nii.gz,Yes,Portal,Just Right,No,3.0,4.0,1.0,True,True,False,NaN,NaN,1.775233e+09
325,NET_0467_0000.nii.gz,Yes,Portal,Just Right,No,3.0,4.0,1.0,False,True,False,NaN,NaN,1.774781e+09

,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,ai_segmentation_quality,manual_segmentation_confidence,adjustment_segmentation_difficulty,high_signal_to_noise,metal_artifacts,patient_motion,other,comment,time-stamp
73,NET_0136_0000.nii.gz,Yes,Arterial,Too Late,No,3.0,1.0,3.0,False,False,False,NaN,Margini di alcune lesioni poco definiti segmen...,1.770805e+09
232,NET_0136_0000.nii.gz,Yes,Arterial,Just Right,No,4.0,3.0,1.0,False,False,False,NaN,NaN,1.768826e+09
103,NET_0218_0000.nii.gz,Yes,Arterial,Too Late,No,4.0,3.0,1.0,False,False,False,NaN,bordi non ben definiti valutazione un po sogge...,1.770745e+09
234,NET_0218_0000.nii.gz,Yes,Arterial,Just Right,No,5.0,4.0,1.0,False,False,False,NaN,NaN,1.768834e+09
153,NET_0271_0000.nii.gz,Yes,Arterial,Too Late,No,4.0,3.0,2.0,False,False,False,NaN,bordi lesione piu grande non ben definiti valu...,1.770747e+09
255,NET_0271_0000.nii.gz,Yes,Arterial,Too Late,No,3.0,3.0,1.0,False,False,False,NaN,NaN,1.769020e+09
80,NET_0274_0000.nii.gz,Partially,Arterial,Too Early,Yes,0.0,0.0,0.0,False,False,False,NaN,nb il fegato e' pressoche' completamente compr...,1.770747e+09
236,NET_0274_0000.nii.gz,Yes,Arterial,Too Early,Yes,NaN,NaN,NaN,False,False,False,NaN,nb fegato pressoche completamente incluso (man...,1.768839e+09
305,NET_0487_0000.nii.gz,Yes,Portal,Too Late,No,4.0,4.0,2.0,False,False,False,NaN,NaN,1.770802e+09
306,NET_0487_0000.nii.gz,Yes,Portal,Too Late,No,4.0,4.0,2.0,False,False,False,NaN,NaN,1.770060e+09
284,NET_0513_0000.nii.gz,Yes,Portal,Too Late,No,3.0,3.0,2.0,False,False,False,NaN,NaN,1.770803e+09
285,NET_0513_0000.nii.gz,Yes,Portal,Too Late,No,3.0,3.0,2.0,False,False,False,NaN,NaN,1.769623e+09
296,NET_0520_0000.nii.gz,Yes,Portal,Just Right,No,0.0,0.0,0.0,False,False,False,NaN,NaN,1.770804e+09
341,NET_0520_0000.nii.gz,Yes,Portal,Just Right,Yes,NaN,NaN,NaN,False,False,False,NaN,NaN,1.770318e+09

,Original File,Destination Folder,New File,SubjectKeyRadiology,ExamDate,file,is_liver_imaged,contrast,phase_timing,is_lesionfree,...,ImageOrientationPatientDICOM,ConversionSoftware,ConversionSoftwareVersion,BodyPartExamined,RawImage,SliceThickness,AcquisitionTime_sec,DICOM_phase,MatchKey,exist_on_server
0,../DICOM-batch3\NKI-d23231-00-0201\20130107 CT...,DICOM-batch3-kalina01,NET_0000_0000.nii.gz,NKI-d23231-00-0201,2013-01-07,NET_0000_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,48979.90000,NaN,NKI-d23231-00-0201_20130107_kalina01_0000.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
481,../DICOM-batch3\NKI-d23231-00-0201\20080219 CT...,DICOM-batch3-kalina99,NET_0000_0000.nii.gz,NKI-d23231-00-0201,2008-02-19,NET_0000_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,CHEST,NaN,3.0,56293.57790,NaN,NKI-d23231-00-0201_20080219_kalina99_0000.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
1,../DICOM-batch3\NKI-d23231-00-0202\20090914 Ab...,DICOM-batch3-kalina01,NET_0001_0000.nii.gz,NKI-d23231-00-0202,2009-09-14,NET_0001_0000.nii.gz,Yes,Arterial,Too Early,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,44652.16987,Arterial,NKI-d23231-00-0202_20090914_kalina01_0001.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
482,../DICOM-batch3\NKI-d23231-00-0201\20080530 CT...,DICOM-batch3-kalina99,NET_0001_0000.nii.gz,NKI-d23231-00-0201,2008-05-30,NET_0001_0000.nii.gz,Yes,Portal,Too Early,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,3.0,33674.38589,NaN,NKI-d23231-00-0201_20080530_kalina99_0001.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
2,../DICOM-batch3\NKI-d23231-00-0204\20080123 Th...,DICOM-batch3-kalina01,NET_0002_0000.nii.gz,NKI-d23231-00-0204,2008-01-23,NET_0002_0000.nii.gz,Yes,Portal,Just Right,Yes,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,50240.38607,NaN,NKI-d23231-00-0204_20080123_kalina01_0002.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,../DICOM-batch3\NKI-d23231-00-0241\20190215 CT...,DICOM-batch3-kalina99,NET_0523_0000.nii.gz,NKI-d23231-00-0241,2019-02-15,NET_0523_0000.nii.gz,Yes,Arterial,Just Right,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,56270.94870,Arterial,NKI-d23231-00-0241_20190215_kalina99_0523.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
479,../DICOM-batch3\NKI-d23231-00-0887\20211130 CT...,DICOM-batch3-kalina01,NET_0524_0000.nii.gz,NKI-d23231-00-0887,2021-11-30,NET_0524_0000.nii.gz,Yes,Portal,Just Right,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,51143.15000,NaN,NKI-d23231-00-0887_20211130_kalina01_0524.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
996,../DICOM-batch3\NKI-d23231-00-0241\20190215 CT...,DICOM-batch3-kalina99,NET_0524_0000.nii.gz,NKI-d23231-00-0241,2019-02-15,NET_0524_0000.nii.gz,Yes,Portal,Just Right,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.5,56329.24349,Portal,NKI-d23231-00-0241_20190215_kalina99_0524.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
480,../DICOM-batch3\NKI-d23231-00-0888\20210526 CT...,DICOM-batch3-kalina01,NET_0525_0000.nii.gz,NKI-d23231-00-0888,2021-05-26,NET_0525_0000.nii.gz,Yes,Portal,Just Right,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,62104.80000,NaN,NKI-d23231-00-0888_20210526_kalina01_0525.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...
997,../DICOM-batch3\NKI-d23231-00-0241\20190913 CT...,DICOM-batch3-kalina99,NET_0525_0000.nii.gz,NKI-d23231-00-0241,2019-09-13,NET_0525_0000.nii.gz,Yes,Portal,Just Right,No,...,"[1, 0, 0, 0, 1, 0]",dcm2niix,v1.0.20230411,ABDOMEN,NaN,1.0,57323.00000,NaN,NKI-d23231-00-0241_20190913_kalina99_0525.nii.gz,\\nki.nl\res\RD CRC-data\_archive\IRBd23231-AM...

In [ ]:
giovanni_batch3 = giovanni_batch3.drop_duplicates(subset="file", keep="first")
christina_batch3 = christina_batch3.drop_duplicates(subset="file", keep="first")

In [50]:
overlap_gc = set(giovanni_batch3["file"]).intersection(christina_batch3["file"])

gc = (
    giovanni_batch3[["file", "contrast"]]
    .merge(
        christina_batch3[["file", "contrast"]],
        on="file",
        suffixes=("_giovanni", "_christina")
    )
)

print(len(overlap_gc))
print("Number of overlapping samples:", len(gc))

344
Number of overlapping samples: 358

In [64]:
from sklearn.metrics import cohen_kappa_score

kappa = cohen_kappa_score(
    gc["contrast_giovanni"],
    gc["contrast_christina"]
)

print(f"Giovanni-Christina Cohen's Kappa: {kappa:.3f}")
pd.crosstab(
    gc["contrast_giovanni"],
    gc["contrast_christina"],
    normalize="all"
)

Giovanni-Christina Cohen's Kappa: 0.968

contrast_christina  Arterial  Non-contrast    Portal
contrast_giovanni
Arterial            0.304469      0.000000  0.005587
Non-contrast        0.000000      0.005587  0.000000
Portal              0.002793      0.005587  0.675978

In [68]:
gk = (
    batch3[["file", "contrast"]]
    .merge(
        giovanni_batch3[["file", "contrast"]],
        on="file",
        suffixes=("_kalina", "_giovanni", )
    )
)

kappa_gk = cohen_kappa_score(
    gk["contrast_giovanni"],
    gk["contrast_kalina"]
)

print(f"Giovanni-Kalina Cohen's Kappa: {kappa_gk:.3f}")
pd.crosstab(
    gk["contrast_giovanni"],
    gk["contrast_kalina"],
    normalize="all"
)

Giovanni-Kalina Cohen's Kappa: 0.395

contrast_kalina           0  Arterial  Non-contrast    Portal
contrast_giovanni
Arterial           0.008646  0.197406      0.037464  0.063401
Non-contrast       0.000000  0.001441      0.001441  0.000000
Portal             0.007205  0.123919      0.073487  0.485591

In [69]:
ck = (
    batch3[["file", "contrast"]]
    .merge(
        christina_batch3[["file", "contrast"]],
        on="file",
        suffixes=("_kalina", "_christina")
    )
)

kappa_ck = cohen_kappa_score(
    ck["contrast_christina"],
    ck["contrast_kalina"]
)

print(f"Kalina-Christina Cohen's Kappa: {kappa_ck:.3f}")
pd.crosstab(
    ck["contrast_christina"],
    ck["contrast_kalina"],
    normalize="all"
)

Kalina-Christina Cohen's Kappa: 0.413

contrast_kalina            0  Arterial  Non-contrast    Portal
contrast_christina
Arterial            0.008646  0.208934      0.040346  0.057637
Non-contrast        0.000000  0.001441      0.001441  0.002882
Portal              0.005764  0.122478      0.070605  0.479827

In [67]:

ck_mismatches = ck[ck["contrast_christina"] != ck["contrast_kalina"]]
gk_mismatches = gk[gk["contrast_giovanni"] != gk["contrast_kalina"]]

print(ck_mismatches["contrast_kalina"].value_counts())
print(gk_mismatches["contrast_kalina"].value_counts())

contrast_kalina
Arterial        86
Non-contrast    77
Portal          42
0               10
Name: count, dtype: int64
contrast_kalina
Arterial        87
Non-contrast    77
Portal          44
0               11
Name: count, dtype: int64

In [60]:
ck

                     file contrast_kalina contrast_christina
0    NET_0000_0000.nii.gz          Portal             Portal
1    NET_0001_0000.nii.gz        Arterial           Arterial
2    NET_0002_0000.nii.gz          Portal             Portal
3    NET_0003_0000.nii.gz          Portal             Portal
4    NET_0004_0000.nii.gz          Portal             Portal
..                    ...             ...                ...
689  NET_0521_0000.nii.gz          Portal             Portal
690  NET_0522_0000.nii.gz          Portal             Portal
691  NET_0523_0000.nii.gz        Arterial             Portal
692  NET_0524_0000.nii.gz          Portal             Portal
693  NET_0525_0000.nii.gz          Portal             Portal

[694 rows x 3 columns]